// Bond Creation module — cashflow / accrued-interest / yield engine.
//
// Standard market conventions (all outputs are labelled INDICATIVE):
//   • Actual/365 day-count for accrued interest and every coupon period.
//   • Coupon dates are generated by stepping BACK from the maturity date by the
//     payment frequency, so the final cashflow always lands on maturity.
//   • Accrued interest = face × coupon% × days(last coupon → settlement)/365.
//     The buyer pays it on top of the clean price and then receives full coupons
//     (matching how a distributor cashflow statement reads).
//   • Partial redemption is parsed best-effort from the maturity text
//     ("X% PARTIAL REDEMPTION STARTING FROM <date> QUARTERLY/… TILL MATURITY");
//     when it cannot be parsed the bond is treated as a bullet (100% at maturity).
//   • TDS on interest defaults to 10% (resident) for the net-receivable column.
//   • Yield is an XIRR (annual compounding, Actual/365) solved from the DIRTY
//     price, so marking the price up correctly lowers the yield.
//
// This engine is confidential-safe: it only uses catalog fields (face value,
// coupon, maturity, payment dates) plus a client-facing price — never cost.

import { parseLeadingDateToISO, inferFrequency } from './bondUtils';

export const TDS_RATE = 0.10;
const SETTLEMENT_LAG_DAYS = 2; // T+2 indicative settlement

export type Frequency = 'Monthly' | 'Quarterly' | 'Half-Yearly' | 'Annual';

export interface CashflowRow {
  date: string;          // ISO
  faceRedeemed: number;  // principal returned on this date (for the whole holding)
  interest: number;      // gross interest
  total: number;         // interest + faceRedeemed
  netAfterTds: number;   // total − TDS on interest
  remark: string;
}

export interface CashflowInput {
  faceValuePerUnit: number | null | undefined;
  coupon: number | null | undefined;            // percent p.a.
  maturityISO: string | null | undefined;
  frequencyHint: string | null | undefined;     // interest_frequency
  ipDates: string | null | undefined;           // interest_payment_dates (fallback)
  redemptionText: string | null | undefined;    // maturity_text (partial-redemption source)
  quantity: number | null | undefined;
  cleanPricePer100: number | null | undefined;   // marked-up client price per ₹100
  settlementISO?: string;
}

export interface CashflowResult {
  ok: boolean;
  reason?: string;
  frequency: Frequency | null;
  settlementDate: string;
  maturityDate: string | null;
  totalFace: number;
  rows: CashflowRow[];
  accruedInterest: number;
  principalAmount: number;    // clean price × quantity
  investmentAmount: number;   // principal + accrued (the EXACT amount payable)
  totalInterest: number;
  totalPrincipalReturned: number;
  assumedBullet: boolean;
}

// ---- date helpers (UTC to avoid tz drift) -----------------------------------
function toDate(iso: string): Date { return new Date(iso + 'T00:00:00Z'); }
function toISO(d: Date): string { return d.toISOString().slice(0, 10); }
function addMonths(d: Date, m: number): Date {
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + m, d.getUTCDate()));
}
function addDays(d: Date, n: number): Date {
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate() + n));
}
function days(a: Date, b: Date): number {
  return Math.round((b.getTime() - a.getTime()) / 86400000);
}

function freqMonths(f: Frequency): number {
  return f === 'Monthly' ? 1 : f === 'Quarterly' ? 3 : f === 'Half-Yearly' ? 6 : 12;
}

function normFrequency(hint: string | null | undefined, ipDates: string | null | undefined): Frequency | null {
  const label = inferFrequency(hint, ipDates);
  if (label === 'Monthly' || label === 'Quarterly' || label === 'Half-Yearly' || label === 'Annual') return label;
  return null;
}

// Best-effort partial-redemption schedule → { couponDateISO: faceRedeemed }.
// Returns null when the text is not a recognised partial-redemption pattern.
function parseRedemption(
  text: string | null | undefined, couponDates: Date[], totalFace: number,
): Record<string, number> | null {
  const t = (text ?? '').trim();
  const pctM = /(\d+(?:\.\d+)?)\s*%\s*(?:partial\s*)?redemption/i.exec(t)
    || /partial\s*redemption[^0-9]*(\d+(?:\.\d+)?)\s*%/i.exec(t);
  if (!pctM) return null;
  const pct = parseFloat(pctM[1]);
  if (!Number.isFinite(pct) || pct <= 0 || pct >= 100) return null;

  const startM = /starting\s+from\s+([0-9]{1,2}[-/\s][A-Za-z0-9]{2,}[-/\s][0-9]{2,4})/i.exec(t);
  const startISO = startM ? parseLeadingDateToISO(startM[1]) : null;
  if (!startISO) return null;

  const cadence: Frequency = /month/i.test(t) ? 'Monthly'
    : /quarter/i.test(t) ? 'Quarterly'
    : /half|semi/i.test(t) ? 'Half-Yearly' : 'Annual';
  const step = freqMonths(cadence);

  const perTranche = totalFace * (pct / 100);
  const maturity = couponDates[couponDates.length - 1];
  const map: Record<string, number> = {};
  let cursor = toDate(startISO);
  let redeemed = 0;
  let guard = 0;
  while (cursor <= maturity && redeemed < totalFace - 0.01 && guard < 200) {
    // snap this tranche to the first coupon date on/after the scheduled date
    const cd = couponDates.find(d => d >= cursor);
    if (!cd) break;
    const amt = Math.min(perTranche, totalFace - redeemed);
    map[toISO(cd)] = (map[toISO(cd)] ?? 0) + amt;
    redeemed += amt;
    cursor = addMonths(cursor, step);
    guard++;
  }
  if (redeemed <= 0) return null;
  return map;
}

export function buildCashflow(input: CashflowInput): CashflowResult {
  const face = input.faceValuePerUnit ?? null;
  const coupon = input.coupon ?? null;
  const qty = input.quantity && input.quantity > 0 ? Math.floor(input.quantity) : 1;
  const settlement = input.settlementISO ? toDate(input.settlementISO) : addDays(new Date(), SETTLEMENT_LAG_DAYS);
  const settlementISO = toISO(settlement);
  const frequency = normFrequency(input.frequencyHint, input.ipDates);

  const empty: CashflowResult = {
    ok: false, frequency, settlementDate: settlementISO, maturityDate: input.maturityISO ?? null,
    totalFace: 0, rows: [], accruedInterest: 0, principalAmount: 0, investmentAmount: 0,
    totalInterest: 0, totalPrincipalReturned: 0, assumedBullet: true,
  };
  if (!face || face <= 0) return { ...empty, reason: 'Face value unknown' };
  if (!coupon || coupon <= 0) return { ...empty, reason: 'Coupon unknown' };
  if (!input.maturityISO) return { ...empty, reason: 'Maturity date unknown' };
  const maturity = toDate(input.maturityISO);
  if (Number.isNaN(maturity.getTime()) || maturity <= settlement) return { ...empty, reason: 'Bond has matured or invalid maturity' };
  const freq = frequency ?? 'Annual';
  const step = freqMonths(freq);

  // Coupon dates: step back from maturity to just after settlement.
  const couponDates: Date[] = [];
  let d = new Date(maturity.getTime());
  let guard = 0;
  while (d > settlement && guard < 1200) { couponDates.unshift(new Date(d.getTime())); d = addMonths(d, -step); guard++; }
  if (couponDates.length === 0) couponDates.push(maturity);
  const lastCoupon = addMonths(couponDates[0], -step); // on/before settlement

  const totalFace = face * qty;
  const cleanPer100 = input.cleanPricePer100 ?? null;

  // Accrued interest (Actual/365) from last coupon to settlement.
  const accruedDays = Math.max(0, days(lastCoupon, settlement));
  const accruedInterest = +(totalFace * (coupon / 100) * (accruedDays / 365)).toFixed(2);

  // Partial redemption schedule (or bullet).
  const redemptionMap = parseRedemption(input.redemptionText, couponDates, totalFace);
  const assumedBullet = !redemptionMap;

  const rows: CashflowRow[] = [];
  let currentFace = totalFace;
  let prev = lastCoupon;
  let totalInterest = 0;
  let totalPrincipalReturned = 0;
  couponDates.forEach((cd, i) => {
    const isMaturity = i === couponDates.length - 1;
    const interest = +(currentFace * (coupon / 100) * (days(prev, cd) / 365)).toFixed(2);
    let redeemed = redemptionMap ? (redemptionMap[toISO(cd)] ?? 0) : 0;
    if (isMaturity) redeemed = currentFace; // return whatever principal remains
    redeemed = +Math.min(redeemed, currentFace).toFixed(2);
    const total = +(interest + redeemed).toFixed(2);
    const net = +(total - interest * TDS_RATE).toFixed(2);
    let remark = '';
    if (isMaturity) remark = 'Maturity : Principal Redemption';
    else if (redeemed > 0) remark = `Part Maturity : Principal Redemption`;
    rows.push({ date: toISO(cd), faceRedeemed: redeemed, interest, total, netAfterTds: net, remark });
    totalInterest += interest;
    totalPrincipalReturned += redeemed;
    currentFace = +(currentFace - redeemed).toFixed(2);
    prev = cd;
  });

  const principalAmount = cleanPer100 !== null ? +(totalFace * (cleanPer100 / 100)).toFixed(2) : 0;
  const investmentAmount = +(principalAmount + accruedInterest).toFixed(2);

  return {
    ok: true, frequency, settlementDate: settlementISO, maturityDate: input.maturityISO,
    totalFace, rows, accruedInterest, principalAmount, investmentAmount,
    totalInterest: +totalInterest.toFixed(2), totalPrincipalReturned: +totalPrincipalReturned.toFixed(2),
    assumedBullet,
  };
}

// XIRR (annual compounding, Actual/365) solved by bisection. `flows` are dated
// gross cashflows to the investor; the dirty price is the outflow at settlement.
function xirr(flows: { date: Date; amount: number }[], settlement: Date, dirtyPrice: number): number | null {
  if (!(dirtyPrice > 0) || flows.length === 0) return null;
  const pts = flows.map(f => ({ t: days(settlement, f.date) / 365, amt: f.amount })).filter(p => p.t > 0);
  if (pts.length === 0) return null;
  const npv = (y: number) => pts.reduce((s, p) => s + p.amt / Math.pow(1 + y, p.t), 0) - dirtyPrice;
  let lo = 1e-5, hi = 1.0, flo = npv(lo), fhi = npv(hi), tries = 0;
  while (flo * fhi > 0 && tries < 80) { hi *= 1.4; fhi = npv(hi); tries++; if (hi > 10) break; }
  if (flo * fhi > 0) return null;
  for (let i = 0; i < 200; i++) {
    const mid = (lo + hi) / 2, fm = npv(mid);
    if (Math.abs(fm) < 1e-7) return mid;
    if (flo * fm < 0) { hi = mid; fhi = fm; } else { lo = mid; flo = fm; }
  }
  return (lo + hi) / 2;
}

// Yield to maturity implied by a client price (per ₹100). Recomputes so that a
// higher price yields less. Returns a percent, or null when it can't be solved.
export function yieldFromPrice(input: Omit<CashflowInput, 'quantity' | 'cleanPricePer100'> & { pricePer100: number | null | undefined }): number | null {
  const price = input.pricePer100 ?? null;
  if (!price || price <= 0) return null;
  // Build a per-₹100 cashflow (quantity 1, face 100).
  const cf = buildCashflow({
    ...input, faceValuePerUnit: 100, quantity: 1, cleanPricePer100: price,
  });
  if (!cf.ok) return null;
  const settlement = toDate(cf.settlementDate);
  const flows = cf.rows.map(r => ({ date: toDate(r.date), amount: r.total }));
  const dirty = price + cf.accruedInterest; // per ₹100
  const y = xirr(flows, settlement, dirty);
  return y === null ? null : +(y * 100).toFixed(2);
}
