// Bond Creation module — cashflow / accrued-interest / yield engine.
//
// Standard market conventions (all outputs are labelled INDICATIVE):
//   • Actual/365 day-count for accrued interest and every coupon period.
//   • Coupon dates are generated by stepping BACK from the maturity date by the
//     payment frequency, so the final cashflow always lands on maturity.
//   • Accrued interest = face × coupon% × days(last coupon → settlement)/365.
//     The buyer pays it on top of the clean price and then receives full coupons
//     (matching how a distributor cashflow statement reads).
//   • Partial redemption is parsed best-effort from the maturity text
//     ("X% PARTIAL REDEMPTION STARTING FROM <date> QUARTERLY/… TILL MATURITY");
//     when it cannot be parsed the bond is treated as a bullet (100% at maturity).
//   • TDS on interest defaults to 10% (resident) for the net-receivable column.
//   • Yield is an XIRR (annual compounding, Actual/365) solved from the DIRTY
//     price, so marking the price up correctly lowers the yield.
//
// This engine is confidential-safe: it only uses catalog fields (face value,
// coupon, maturity, payment dates) plus a client-facing price — never cost.

import { parseLeadingDateToISO, inferFrequency } from './bondUtils';

export const TDS_RATE = 0.10;
const SETTLEMENT_LAG_DAYS = 2; // T+2 indicative settlement

// Book-closure / record-date window before a coupon. Many bonds freeze the
// interest register ~15 days before payout: whoever holds the unit in demat on
// the record date receives that coupon, EVEN IF the bond is transferred to
// another DP afterwards. So a buyer who settles inside this window buys
// "ex-interest" — they do not receive that upcoming coupon and instead get a
// negative accrued (a price rebate for the days they hold before it).
export const RECORD_DATE_FREEZE_DAYS = 15;

export type Frequency = 'Monthly' | 'Quarterly' | 'Half-Yearly' | 'Annual';

export interface CashflowRow {
  date: string;          // ISO
  faceRedeemed: number;  // principal returned on this date (for the whole holding)
  interest: number;      // gross interest
  total: number;         // interest + faceRedeemed
  netAfterTds: number;   // total − TDS on interest
  remark: string;
}

export interface CashflowInput {
  faceValuePerUnit: number | null | undefined;
  coupon: number | null | undefined;            // percent p.a.
  maturityISO: string | null | undefined;
  frequencyHint: string | null | undefined;     // interest_frequency
  ipDates: string | null | undefined;           // interest_payment_dates (fallback)
  redemptionText: string | null | undefined;    // maturity_text (partial-redemption source)
  quantity: number | null | undefined;
  cleanPricePer100: number | null | undefined;   // marked-up client price per ₹100
  settlementISO?: string;
}

export interface CashflowResult {
  ok: boolean;
  reason?: string;
  frequency: Frequency | null;
  settlementDate: string;
  maturityDate: string | null;
  totalFace: number;
  rows: CashflowRow[];
  accruedInterest: number;
  principalAmount: number;    // clean price × quantity
  investmentAmount: number;   // principal + accrued (the EXACT amount payable)
  totalInterest: number;
  totalPrincipalReturned: number;
  assumedBullet: boolean;
  exInterest: boolean;   // settlement fell in the record-date window (see above)
}

// ---- date helpers (UTC to avoid tz drift) -----------------------------------
function toDate(iso: string): Date { return new Date(iso + 'T00:00:00Z'); }
function toISO(d: Date): string { return d.toISOString().slice(0, 10); }
function addMonths(d: Date, m: number): Date {
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + m, d.getUTCDate()));
}
function addDays(d: Date, n: number): Date {
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate() + n));
}
function days(a: Date, b: Date): number {
  return Math.round((b.getTime() - a.getTime()) / 86400000);
}

function freqMonths(f: Frequency): number {
  return f === 'Monthly' ? 1 : f === 'Quarterly' ? 3 : f === 'Half-Yearly' ? 6 : 12;
}

function normFrequency(hint: string | null | undefined, ipDates: string | null | undefined): Frequency | null {
  const label = inferFrequency(hint, ipDates);
  if (label === 'Monthly' || label === 'Quarterly' || label === 'Half-Yearly' || label === 'Annual') return label;
  return null;
}

interface RedemptionPlan {
  events: { date: Date; amount: number }[]; // future tranches (after settlement)
  preSettlementRedeemed: number;            // principal already returned before settlement
}

// Best-effort partial-redemption schedule parsed from the maturity text, e.g.
// "25% PARTIAL REDEMPTION STARTING FROM 28 FEB 2029 QUATERLY TILL MATURITY"
// → 25% of the ORIGINAL face returned each quarter from that date. Tranches are
// generated on their OWN cadence (not snapped to coupon dates), so interest can
// be computed on the reducing balance regardless of the payout frequency.
// Returns null when the text is not a recognised partial-redemption pattern.
function parseRedemption(
  text: string | null | undefined, maturity: Date, settlement: Date, totalFace: number,
): RedemptionPlan | null {
  const t = (text ?? '').trim();
  const pctM = /(\d+(?:\.\d+)?)\s*%\s*(?:partial\s*)?redemption/i.exec(t)
    || /partial\s*redemption[^0-9]*(\d+(?:\.\d+)?)\s*%/i.exec(t);
  if (!pctM) return null;
  const pct = parseFloat(pctM[1]);
  if (!Number.isFinite(pct) || pct <= 0 || pct >= 100) return null;

  const startM = /starting\s+from\s+([0-9]{1,2}[-/\s][A-Za-z0-9]{2,}[-/\s][0-9]{2,4})/i.exec(t);
  const startISO = startM ? parseLeadingDateToISO(startM[1]) : null;
  if (!startISO) return null;

  // Cadence — tolerant of the common "QUATERLY" misspelling and "qtr".
  const cadence: Frequency = /month/i.test(t) ? 'Monthly'
    : /quart|quater|qtr/i.test(t) ? 'Quarterly'
    : /half|semi/i.test(t) ? 'Half-Yearly' : 'Annual';
  const step = freqMonths(cadence);

  const perTranche = +(totalFace * (pct / 100)).toFixed(2);
  const events: { date: Date; amount: number }[] = [];
  let cursor = toDate(startISO);
  let redeemed = 0;
  let preSettlementRedeemed = 0;
  let guard = 0;
  while (cursor <= maturity && redeemed < totalFace - 0.01 && guard < 600) {
    const amount = +Math.min(perTranche, totalFace - redeemed).toFixed(2);
    if (cursor > settlement) events.push({ date: new Date(cursor.getTime()), amount });
    else preSettlementRedeemed += amount; // already returned to the prior holder
    redeemed += amount;
    cursor = addMonths(cursor, step);
    guard++;
  }
  if (redeemed <= 0) return null;
  return { events, preSettlementRedeemed: +preSettlementRedeemed.toFixed(2) };
}

export function buildCashflow(input: CashflowInput): CashflowResult {
  const face = input.faceValuePerUnit ?? null;
  const coupon = input.coupon ?? null;
  const qty = input.quantity && input.quantity > 0 ? Math.floor(input.quantity) : 1;
  const settlement = input.settlementISO ? toDate(input.settlementISO) : addDays(new Date(), SETTLEMENT_LAG_DAYS);
  const settlementISO = toISO(settlement);
  const frequency = normFrequency(input.frequencyHint, input.ipDates);

  const empty: CashflowResult = {
    ok: false, frequency, settlementDate: settlementISO, maturityDate: input.maturityISO ?? null,
    totalFace: 0, rows: [], accruedInterest: 0, principalAmount: 0, investmentAmount: 0,
    totalInterest: 0, totalPrincipalReturned: 0, assumedBullet: true, exInterest: false,
  };
  if (!face || face <= 0) return { ...empty, reason: 'Face value unknown' };
  if (!coupon || coupon <= 0) return { ...empty, reason: 'Coupon unknown' };
  if (!input.maturityISO) return { ...empty, reason: 'Maturity date unknown' };
  const maturity = toDate(input.maturityISO);
  if (Number.isNaN(maturity.getTime()) || maturity <= settlement) return { ...empty, reason: 'Bond has matured or invalid maturity' };
  const freq = frequency ?? 'Annual';
  const step = freqMonths(freq);

  // Coupon dates: step back from maturity to just after settlement.
  const couponDates: Date[] = [];
  let d = new Date(maturity.getTime());
  let guard = 0;
  while (d > settlement && guard < 1200) { couponDates.unshift(new Date(d.getTime())); d = addMonths(d, -step); guard++; }
  if (couponDates.length === 0) couponDates.push(maturity);
  const lastCoupon = addMonths(couponDates[0], -step); // on/before settlement

  const totalFace = face * qty;                       // notional at issue
  const cleanPer100 = input.cleanPricePer100 ?? null;

  // Partial redemption plan (tranches on their own cadence) — or bullet.
  const plan = parseRedemption(input.redemptionText, maturity, settlement, totalFace);
  const assumedBullet = !plan;
  // Face outstanding at purchase = original less anything already redeemed.
  const outstandingAtBuy = +(totalFace - (plan?.preSettlementRedeemed ?? 0)).toFixed(2);

  // Record-date / ex-interest test: is settlement inside the freeze window before
  // the next coupon? If so the seller (registered holder on the record date)
  // keeps that coupon, so the buyer gets a NEGATIVE accrued (rebate) instead of
  // paying accrued, and does not receive the first coupon.
  const nextCoupon = couponDates[0];
  const daysToNext = days(settlement, nextCoupon);
  const exInterest = daysToNext >= 0 && daysToNext <= RECORD_DATE_FREEZE_DAYS;

  // Accrued interest is on the CURRENT outstanding balance.
  const accruedInterest = exInterest
    ? -(+(outstandingAtBuy * (coupon / 100) * (daysToNext / 365)).toFixed(2))
    : +(outstandingAtBuy * (coupon / 100) * (Math.max(0, days(lastCoupon, settlement)) / 365)).toFixed(2);

  // Assign each redemption tranche to the nearest coupon date (within half a
  // coupon period) so principal + interest land on one row; a tranche with no
  // nearby coupon keeps its own date. Interest is then computed on the reducing
  // balance across the merged timeline — independent of the payout frequency.
  const couponSet = new Set(couponDates.map(toISO));
  const redMap: Record<string, number> = {};
  const extraDates: Date[] = [];
  const halfPeriod = (step * 30) / 2 + 5;
  if (plan) {
    for (const ev of plan.events) {
      let best: Date | null = null; let bestDiff = Infinity;
      for (const cd of couponDates) {
        const diff = Math.abs(days(cd, ev.date));
        if (diff < bestDiff) { bestDiff = diff; best = cd; }
      }
      const key = best && bestDiff <= halfPeriod ? toISO(best) : toISO(ev.date);
      if (!couponSet.has(key)) extraDates.push(ev.date);
      redMap[key] = +((redMap[key] ?? 0) + ev.amount).toFixed(2);
    }
  }

  const eventISO = Array.from(new Set([...couponDates.map(toISO), ...extraDates.map(toISO)])).sort();
  const maturityISOstr = toISO(maturity);

  const rows: CashflowRow[] = [];
  let outstanding = outstandingAtBuy;
  let prev = lastCoupon;
  let interestAccum = 0;
  let totalInterest = 0;
  let totalPrincipalReturned = 0;

  eventISO.forEach((iso, i) => {
    const ev = toDate(iso);
    const isMaturity = iso === maturityISOstr || i === eventISO.length - 1;
    const isCoupon = couponSet.has(iso) || isMaturity;
    interestAccum += outstanding * (coupon / 100) * (days(prev, ev) / 365);

    // Ex-interest: the first coupon's interest is paid to the registered holder
    // on the record date (the seller), not the buyer.
    const toSeller = i === 0 && exInterest && isCoupon;
    let interest = 0;
    if (toSeller) { interestAccum = 0; }                  // coupon taken by the seller
    else if (isCoupon) { interest = +interestAccum.toFixed(2); interestAccum = 0; }
    // else: a redemption-only date — interest carries to the next coupon.

    let redeemed = redMap[iso] ?? 0;
    if (isMaturity) redeemed = outstanding;               // return remaining principal
    redeemed = +Math.min(redeemed, outstanding).toFixed(2);

    const total = +(interest + redeemed).toFixed(2);
    const net = +(total - interest * TDS_RATE).toFixed(2);
    let remark = '';
    if (toSeller) remark = 'Interest to registered holder (record date)';
    else if (isMaturity) remark = totalPrincipalReturned > 0 ? 'Final Redemption' : 'Maturity : Principal Redemption';
    else if (redeemed > 0) remark = 'Part Redemption';

    rows.push({ date: iso, faceRedeemed: redeemed, interest, total, netAfterTds: net, remark });
    totalInterest += interest;
    totalPrincipalReturned += redeemed;
    outstanding = +(outstanding - redeemed).toFixed(2);
    prev = ev;
  });

  const principalAmount = cleanPer100 !== null ? +(outstandingAtBuy * (cleanPer100 / 100)).toFixed(2) : 0;
  const investmentAmount = +(principalAmount + accruedInterest).toFixed(2);

  return {
    ok: true, frequency, settlementDate: settlementISO, maturityDate: input.maturityISO,
    totalFace: outstandingAtBuy, rows, accruedInterest, principalAmount, investmentAmount,
    totalInterest: +totalInterest.toFixed(2), totalPrincipalReturned: +totalPrincipalReturned.toFixed(2),
    assumedBullet, exInterest,
  };
}

// XIRR (annual compounding, Actual/365) solved by bisection. `flows` are dated
// gross cashflows to the investor; the dirty price is the outflow at settlement.
function xirr(flows: { date: Date; amount: number }[], settlement: Date, dirtyPrice: number): number | null {
  if (!(dirtyPrice > 0) || flows.length === 0) return null;
  const pts = flows.map(f => ({ t: days(settlement, f.date) / 365, amt: f.amount })).filter(p => p.t > 0);
  if (pts.length === 0) return null;
  const npv = (y: number) => pts.reduce((s, p) => s + p.amt / Math.pow(1 + y, p.t), 0) - dirtyPrice;
  let lo = 1e-5, hi = 1.0, flo = npv(lo), fhi = npv(hi), tries = 0;
  while (flo * fhi > 0 && tries < 80) { hi *= 1.4; fhi = npv(hi); tries++; if (hi > 10) break; }
  if (flo * fhi > 0) return null;
  for (let i = 0; i < 200; i++) {
    const mid = (lo + hi) / 2, fm = npv(mid);
    if (Math.abs(fm) < 1e-7) return mid;
    if (flo * fm < 0) { hi = mid; fhi = fm; } else { lo = mid; flo = fm; }
  }
  return (lo + hi) / 2;
}

// Yield to maturity implied by a client price (per ₹100). Recomputes so that a
// higher price yields less. Returns a percent, or null when it can't be solved.
export function yieldFromPrice(input: Omit<CashflowInput, 'quantity' | 'cleanPricePer100'> & { pricePer100: number | null | undefined }): number | null {
  const price = input.pricePer100 ?? null;
  if (!price || price <= 0) return null;
  // Build a per-₹100 cashflow (quantity 1, face 100).
  const cf = buildCashflow({
    ...input, faceValuePerUnit: 100, quantity: 1, cleanPricePer100: price,
  });
  if (!cf.ok) return null;
  const settlement = toDate(cf.settlementDate);
  const flows = cf.rows.map(r => ({ date: toDate(r.date), amount: r.total }));
  const dirty = price + cf.accruedInterest; // per ₹100
  const y = xirr(flows, settlement, dirty);
  return y === null ? null : +(y * 100).toFixed(2);
}
